### ISSUE TITLE
Custom transalations table

### ISSUE THREAD

**Issue by shoba-menon** [zzeligg/zlocalize#1]
Hi,
Ours is a SaaS based application and we have 120+ models. With some of the entities having around thousands of records. We have to support multiple languages and hence plan to use zlocalize gem. The only issue we foresee is, with only one translations table, the system would soon experience performance issues.
Can we have separate table to store each model's translations in a separate table to improve the performance?

**Comment by zzeligg** [comment]
Hi,

I assume you are talking about the Attached Translations functionality, which you use by declaring has_translations on your models.

If you have (for example) 10 000 records for each of your 120 models, which have 5 attributes each for 10 languages then you would end up with:

10 000 x 120 x 5 x 10 = 60 000 000 translation records, requiring a composite index on 3 columns…

Which is indeed a lot of rows and can impact performance… 

If you wish to separate translations into more tables, you will have to roll out your own solution. It might be something I would eventually add to ZLocalize, but I have not had the need for it myself.

I have not seen your exact use case for translations, but another conceivable way to solve this could be declare a single TEXT (or JSON) column on each model, which would store all the translation data for each record. This way, each record carries its own translation payload. So if you’re mainly retrieving small subsets in a paged list or displaying records one by one on a page, then it is not too expensive.  Also, it is relatively simple to implement a single module (a concern) to be included in your models, which would handle retrieving and assigning the translation data.

Of course, all this depends on how your application uses the translations. For example, if you have to search within the translated data, it would require indexes to achieve decent performance. But even that could be solved, I think, with MySQL 5.7, which supports the native JSON data type, and allows to query it and create indices that lookup specific values inside JSON data objects or arrays…

It is not a trivial use case you are faced with. It certainly requires some level of thought, design and experimentation.

Regards,

Charles Bedard
